import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Box, Button, Typography, CircularProgress, Paper, Grid } from '@mui/material'
import { fetchReports } from '@store/slices/reportSlice'
import DataTable from '@components/common/DataTable'
import Modal from '@components/common/Modal'
import AddIcon from '@mui/icons-material/Add'
import FileDownloadIcon from '@mui/icons-material/FileDownload'

const Reports = () => {
  const dispatch = useDispatch()
  const { reports, loading } = useSelector((state) => state.report)
  const [openCreateModal, setOpenCreateModal] = useState(false)

  useEffect(() => {
    dispatch(fetchReports())
  }, [dispatch])

  const columns = [
    { key: 'title', label: 'Report Title' },
    { key: 'type', label: 'Type' },
    { key: 'generatedDate', label: 'Generated Date' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'status', label: 'Status' },
  ]

  const handleDownload = (report) => {
    console.log('Downloading report:', report.id)
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4">Reports</Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => setOpenCreateModal(true)}
        >
          Generate Report
        </Button>
      </Box>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '400px' }}>
          <CircularProgress />
        </Box>
      ) : (
        <DataTable columns={columns} rows={reports} exportable selectable />
      )}

      <Modal
        open={openCreateModal}
        title="Generate New Report"
        onClose={() => setOpenCreateModal(false)}
      >
        <Typography>Form for generating new report</Typography>
      </Modal>
    </Box>
  )
}

export default Reports
